---
title: "Milestone 2"
author: "Minjue Wu"
date: "9/20/2019"
output: html_document
---

### Project 1: [SETTLING THE DUST: Air Pollution & Public Opinion in China, 2012](https://ruoqi-zhang.shinyapps.io/weibo_air_quality/)

At first glance, I thought this project would just analyze the statistical correlations between general rising pollution and social media posts in China using sentiment score. Although it was apparent that such an analysis could not be done given the numerical uncertainties introduced by increasing government censorship of Weibo posts near the end of 2013, I was impressed by the geopolitical scope of the data as well as recovery of the content of specific censored posts. This project drew from international data sources, and likely needed a lot of cleaning and gathering, especially in the translational portion of the censorship keyword searchups. The color coded pollution maps of China and timescale in particular were greatly effective for highlighting (literally) the core affected sectors. The plot of PM2.5 density versus Average Weibo Sentiment was a chillingly effective way of contrasting the stagnant "public sentiment" against the drastic shifts in pollution -- it is an almost undeniable persuasion for the significance of the project in environmental terms, as well as the pervasive role of censorship in suppressing variations in public thought. I think one way to strengthen the analysis is to clarify whether graphs of "Number of Weibo posts that mention X" included the now- censored information, or simply the posts that were still publically accessible in Spring 2019. A great way to synthesize the four sections of Settling The Dust would have been to combine the Keywords search function with the final "Rising Trends in Censorship Data", showing how much environment representation was present in the censored data. As it stands, the project is a beautiful compilation of visualized data and shows how concurrent trends occur individually over time, but the data itself doesn't really tie together the relationship between pollution/public opinion/censorship, as it doesn't seem to contextualize multiple aspects like "subscription bases", "keywords", "urban development", and "censorship trends" within one graph.     

### Project 2: [Game of Thrones](https://tategreen.shinyapps.io/Word_Cloud/)

I thought the concept of this project was very interesting and definitely a fun way to break down the worldbuilding power of a script down to its barest components. The Word Cloud was a striking way to highlight which words dominate Westeros -- for example, hierarchical terms like "lord", "boy", "lady", "kings", and "(your) grace" consistently show up as top picks in every season, emphasizing the show's focus on interaction between social castes. I thought it would have been neat if the graphs could also be changed season by season to show numerical data for the top 20 words, and an explanation would be given on how "negative" and "positive" words were determined. Furthermore, I think more interesting results may have surfaced with further filtering of common terms like "youre" and "ive", especially when increasing the minimum frequency of the word. Overall, the strong point of the project is its clean visual presentation, aside from a tendency for the bottom line of words on the Word Cloud to be obscured. Since all the data were from the scripts, it likely didn't need require extensive data cleaning, so it would have been great to also analyze the correlations between words, characters, and/or setting in the script (does the rapid appearance of one key term precede another? do certain characters have unusual setting associations? etc.) 